import {useEffect,useState} from 'react';
import {KeyRound,LogOut,Plus,RotateCw,ShieldCheck,Trash2,Copy,Check} from 'lucide-react';
import type {DeveloperSession} from '../../../src/developer-auth/types';
import {getStoredSession,login,logout,register} from './auth';
import {createApiKey,listApiKeys,revokeApiKey,rotateApiKey,type ApiKey} from './apiKeys';

function App(){
  const [session,setSession]=useState<DeveloperSession|null>(getStoredSession());
  const [registerMode,setRegisterMode]=useState(false);
  if(!session) return <AuthScreen registerMode={registerMode} setRegisterMode={setRegisterMode} onAuth={setSession}/>;
  return <Dashboard session={session} onLogout={()=>{logout();setSession(null)}}/>;
}
function AuthScreen({registerMode,setRegisterMode,onAuth}:{registerMode:boolean;setRegisterMode:(v:boolean)=>void;onAuth:(s:DeveloperSession)=>void}){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{onAuth(registerMode?await register(email,password):await login(email,password));}catch(err){setError(err instanceof Error?err.message:'Authentication failed');}finally{setBusy(false)}}
  return <main className="auth-shell"><section className="auth-card"><div className="brand"><div className="brand-mark"><KeyRound/></div><div><strong>QR Tools</strong><span>Developer Portal</span></div></div><h1>{registerMode?'Create developer account':'Sign in'}</h1><p className="muted">Manage API keys and integrate with the QR Tools API.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} autoComplete={registerMode?'new-password':'current-password'}/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':registerMode?'Create account':'Sign in'}</button></form><button className="link" onClick={()=>setRegisterMode(!registerMode)}>{registerMode?'Already have an account? Sign in':'Need an account? Create one'}</button></section></main>
}
function Dashboard({session,onLogout}:{session:DeveloperSession;onLogout:()=>void}){
 const [keys,setKeys]=useState<ApiKey[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showCreate,setShowCreate]=useState(false),[name,setName]=useState(''),[secret,setSecret]=useState(''),[copied,setCopied]=useState(false);
 async function refresh(){setLoading(true);setError('');try{const d=await listApiKeys(session);setKeys(d.keys??[])}catch(e){setError(e instanceof Error?e.message:'Unable to load API keys')}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 async function create(){if(!name.trim())return;try{const d=await createApiKey(session,name.trim());setSecret(d.key.secret);setName('');setShowCreate(false);await refresh()}catch(e){setError(e instanceof Error?e.message:'Create failed')}}
 async function revoke(id:string){if(!confirm('Revoke this API key? Existing integrations using it will stop working.'))return;try{await revokeApiKey(session,id);await refresh()}catch(e){setError(e instanceof Error?e.message:'Revoke failed')}}
 async function rotate(id:string){if(!confirm('Rotate this API key? The current key will stop working.'))return;try{const d=await rotateApiKey(session,id);setSecret(d.key.secret);await refresh()}catch(e){setError(e instanceof Error?e.message:'Rotate failed')}}
 async function copy(){await navigator.clipboard.writeText(secret);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 return <div className="app"><header><div className="brand"><div className="brand-mark"><KeyRound/></div><div><strong>QR Tools</strong><span>Developer Portal</span></div></div><div className="account"><span>{session.user.email}</span><button className="icon-button" title="Sign out" onClick={onLogout}><LogOut size={18}/></button></div></header><aside><nav><a className="active"><KeyRound size={17}/>API Keys</a><a className="disabled">Usage</a><a className="disabled">API Test</a><a className="disabled">Documentation</a></nav></aside><main className="content"><div className="page-head"><div><div className="eyebrow">Developer</div><h1>API Keys</h1><p className="muted">Create and manage credentials for <code>api.thangdc.com</code>.</p></div><button className="primary" onClick={()=>setShowCreate(true)}><Plus size={17}/>Create API key</button></div>{error&&<div className="error banner">{error}</div>}{loading?<div className="empty">Loading API keys…</div>:keys.length===0?<div className="empty"><ShieldCheck size={30}/><h2>No API keys yet</h2><p>Create your first key to start integrating.</p><button className="primary" onClick={()=>setShowCreate(true)}><Plus size={17}/>Create API key</button></div>:<div className="table-card"><table><thead><tr><th>Name</th><th>Key</th><th>Status</th><th>Created</th><th>Last used</th><th></th></tr></thead><tbody>{keys.map(k=><tr key={k.id}><td><strong>{k.name}</strong><small>{k.rate_limit_per_minute} requests/min</small></td><td><code>{k.key_masked}</code></td><td><span className={`status ${k.status}`}>{k.status}</span></td><td>{new Date(k.created_at).toLocaleDateString()}</td><td>{k.last_used_at?new Date(k.last_used_at).toLocaleDateString():'Never'}</td><td className="actions">{k.status==='active'&&<><button title="Rotate" onClick={()=>rotate(k.id)}><RotateCw size={16}/></button><button title="Revoke" onClick={()=>revoke(k.id)}><Trash2 size={16}/></button></>}</td></tr>)}</tbody></table></div>}<p className="security-note"><ShieldCheck size={16}/> API keys are shown in full only once when created or rotated. Store them securely.</p></main>{(showCreate||secret)&&<div className="modal-backdrop"><div className="modal">{secret?<><h2>API key created</h2><p className="muted">Copy this key now. It will not be shown again.</p><div className="secret"><code>{secret}</code><button onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><div className="warning">Treat this key like a password. Never commit it to source control.</div><button className="primary full" onClick={()=>setSecret('')}>Done</button></>:<><h2>Create API key</h2><label>Key name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Production integration" autoFocus maxLength={100}/></label><div className="modal-actions"><button className="secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="primary" onClick={create} disabled={!name.trim()}>Create key</button></div></>}</div></div>}</div>
}
export default App;