import { QRTemplate, QRDesignOptions } from '../types/qr';

export const BASE_DESIGN: QRDesignOptions = {
  fgColor: '#000000',
  bgColor: '#ffffff',
  margin: 2,
  errorCorrectionLevel: 'M',
  centerLogo: 'none',
  customLogoUrl: null,
  resolution: 1024,
  moduleStyle: 'square',
  eyeStyle: 'square',
  frameStyle: 'none',
  frameText: 'SCAN ME',
};

export const PREDEFINED_TEMPLATES: QRTemplate[] = [
  {
    id: 'tmpl-clean-bare',
    name: 'Clean Bare QR',
    description: 'Pure QR code with no border card. Perfect for graphic handoffs.',
    isPredefined: true,
    isDefault: true,
    layout: 'bare',
    headerTitle: '',
    footerMessage: '',
    includeWifi: false,
    frameStyle: 'none',
    frameText: '',
    design: {
      ...BASE_DESIGN,
      moduleStyle: 'square',
      eyeStyle: 'square',
    },
  },
  {
    id: 'tmpl-scanme-frame',
    name: 'Scan Me Callout',
    description: 'QR code with high-contrast bottom call-to-action banner.',
    isPredefined: true,
    isDefault: false,
    layout: 'framed',
    headerTitle: '',
    footerMessage: '',
    includeWifi: false,
    frameStyle: 'bottom-bar',
    frameText: 'SCAN ME',
    design: {
      ...BASE_DESIGN,
      frameStyle: 'bottom-bar',
      frameText: 'SCAN ME',
      moduleStyle: 'squircle',
      eyeStyle: 'rounded',
    },
  },
  {
    id: 'tmpl-table-tent',
    name: 'Restaurant Table Tent',
    description: 'Menu order card with Table Number header and guest Wi-Fi details.',
    isPredefined: true,
    isDefault: false,
    layout: 'table-tent',
    headerTitle: 'MENU & ĐẶT MÓN',
    subtitle: 'Quét để xem thực đơn và gọi món',
    footerMessage: 'Mở camera điện thoại quét mã',
    includeWifi: true,
    wifiSsid: 'Cafe_FreeWifi',
    wifiPass: 'coffee2026',
    frameStyle: 'none',
    frameText: '',
    design: {
      ...BASE_DESIGN,
      moduleStyle: 'dots',
      eyeStyle: 'circle',
    },
  },
  {
    id: 'tmpl-vietqr-stand',
    name: 'VietQR Counter Stand',
    description: 'Napas 247 banking payment stand for store cashiers.',
    isPredefined: true,
    isDefault: false,
    layout: 'bank-stand',
    headerTitle: 'THANH TOÁN CHUYỂN KHOẢN',
    subtitle: 'VietQR · Napas 247 Instant Transfer',
    footerMessage: 'Quét bằng app ngân hàng bất kỳ (VCB, MB, Techcom...)',
    includeWifi: false,
    frameStyle: 'none',
    frameText: '',
    design: {
      ...BASE_DESIGN,
      centerLogo: 'bank',
      errorCorrectionLevel: 'H',
      moduleStyle: 'square',
      eyeStyle: 'square',
    },
  },
  {
    id: 'tmpl-minimal-plaque',
    name: 'Minimal Desk Plaque',
    description: 'Elegant desktop card for reception counters and meeting rooms.',
    isPredefined: true,
    isDefault: false,
    layout: 'minimal-card',
    headerTitle: 'SCAN TO CONNECT',
    subtitle: 'Official Company Directory',
    footerMessage: 'Thank you for visiting',
    includeWifi: false,
    frameStyle: 'none',
    frameText: '',
    design: {
      ...BASE_DESIGN,
      moduleStyle: 'squircle',
      eyeStyle: 'rounded',
    },
  },
  {
    id: 'tmpl-dark-card',
    name: 'Dark Slate Studio Card',
    description: 'Modern obsidian dark theme card with high-contrast QR display.',
    isPredefined: true,
    isDefault: false,
    layout: 'dark-card',
    headerTitle: 'DIGITAL ACCESS',
    subtitle: 'Scan for exclusive access',
    footerMessage: 'Secure NFC & Camera Scan',
    includeWifi: false,
    frameStyle: 'none',
    frameText: '',
    design: {
      ...BASE_DESIGN,
      fgColor: '#000000',
      bgColor: '#ffffff',
      moduleStyle: 'squircle',
      eyeStyle: 'rounded',
    },
  },
];
